// @generated by scripts/generate-agent-entry.mjs. Do not edit manually.

export const STRATA_AGENT_HARNESS = {
  "schema_version": 1,
  "harness_version": "1.0",
  "contract_version": "1.1",
  "name": "Strata Agent Harness",
  "summary": "A capability-gated workflow and executable action graph for agents that discover, read market and account state, quote, prepare, externally sign, and submit Strata operations.",
  "entrypoints": {
    "documentation": "https://stratabook.org/docs/agent-harness/",
    "capabilities": "https://api.stratabook.app/sonar/capabilities",
    "markets": "https://api.stratabook.app/sonar/markets",
    "platform_capabilities": "https://api.stratabook.app/v2/capabilities",
    "platform_markets": "https://api.stratabook.app/v2/markets",
    "action_graph": "https://api.stratabook.app/sonar/action-graph",
    "mcp": "https://api.stratabook.app/mcp",
    "manifest": "https://api.stratabook.app/.well-known/strata-agent.json"
  },
  "interfaces": {
    "mcp_tool_order": [
      "strata_capabilities",
      "strata_action_graph",
      "strata_markets",
      "strata_quote",
      "strata_execution_challenge",
      "strata_execution_prepare",
      "strata_execution_submit"
    ],
    "terminal": [
      "npx -y @stratabook/sdk capabilities --json",
      "npx -y @stratabook/sdk action-graph --json",
      "npx -y @stratabook/sdk markets --json",
      "npx -y @stratabook/sdk quote --market SOL/USDC --side sell --amount-atoms 10000000 --json"
    ]
  },
  "workflow": [
    {
      "id": "discover_capabilities",
      "instruction": "Read the live capability catalog before every objective. Never infer permission from documentation, package support, or an earlier session."
    },
    {
      "id": "establish_mode",
      "instruction": "Read the action graph and identify which prepare and submit nodes are live. The external agent owner configures its permissions and signer authority; static documentation never enables a Strata operation."
    },
    {
      "id": "understand_objective",
      "instruction": "Resolve the user's market, side, amount, and tolerance. Ask before proceeding when any economically meaningful input is ambiguous."
    },
    {
      "id": "discover_market",
      "instruction": "List markets, select one marked ready, and use its discovered base and quote decimals. Do not guess market identifiers or token decimals."
    },
    {
      "id": "read_market_data",
      "instruction": "When books.read is live, use the opaque market ID to read the Strata book, status, fees, and recent trades. Subscribe to the market stream for changes and recover from any sequence gap with a fresh snapshot."
    },
    {
      "id": "read_account",
      "instruction": "When account.read is live, use the owner-configured signer to authorize the exact wallet, market, request time, and fill limit. Read or stream only the sanitized orders and fills returned by the official SDK, and recover stream gaps from a fresh signed snapshot."
    },
    {
      "id": "preserve_atoms",
      "instruction": "Represent token amounts as unsigned base-10 atomic strings. Never pass settlement amounts through floating-point arithmetic."
    },
    {
      "id": "request_quote",
      "instruction": "Request a fresh Sonar quote with an explicit side, exact input atoms, and execution tolerance supplied by the external agent."
    },
    {
      "id": "validate_quote",
      "instruction": "Verify the quote binds to the selected market, side, and input. Check labelled fees, minimum output, price impact, server time, and expiry."
    },
    {
      "id": "report_result",
      "instruction": "Report consumed input, expected output, minimum output, fees by asset side, price impact, and remaining validity."
    },
    {
      "id": "authorize_writes",
      "instruction": "When prepare and submit are exposed, keep signing external to Strata: request canonical authorization bytes, sign them with the owner-configured signer, verify the prepared transaction preserves the quote, then submit the externally signed transaction with idempotency."
    },
    {
      "id": "monitor_outcome",
      "instruction": "After an authorized submission, report the durable receipt or explicit failure. Never claim completion from preparation, signing, or an unconfirmed request."
    }
  ],
  "stop_conditions": [
    "The required live capability is disabled or absent.",
    "The market is paused, unavailable, or has no reviewed operation path.",
    "Market, side, amount, decimals, tolerance, or signer authority is unavailable or ambiguous.",
    "The contract version is unsupported or a response contains unknown fields.",
    "A quote is expired or its market, side, amount, fee, minimum-output, or time binding is inconsistent.",
    "A requested operation exceeds the exposed tool, account, or policy scope.",
    "A user asks the agent to receive or expose wallet secrets, private keys, seed phrases, session keys, or production credentials."
  ],
  "safety_rules": [
    "Never request or accept wallet secrets, private keys, seed phrases, session keys, or production credentials in a prompt.",
    "Never call undocumented endpoints or reconstruct private Sonar behavior.",
    "Never silently widen slippage, refresh changed economics, substitute a market, or retry a non-retryable failure.",
    "Treat capability removal, revocation, expiry, and emergency disable as immediate stop signals.",
    "Capability and action-graph availability are authoritative for Strata operations; permission and signer policy remain controlled by the external agent owner."
  ]
} as const;

export const STRATA_AGENT_HARNESS_URI = "strata://agent-harness/v1";

export const STRATA_ACTION_GRAPH = {
  "schema_version": 1,
  "graph_version": "1.0",
  "contract_version": "1.1",
  "entry_node": "discover_capabilities",
  "authority": {
    "permission_source": "external_agent_owner",
    "signing_location": "external",
    "accepts_private_keys": false
  },
  "nodes": [
    {
      "id": "discover_capabilities",
      "kind": "discovery",
      "summary": "Read the live capabilities that currently expose Strata operations.",
      "required_capabilities": [],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/sonar/capabilities",
        "mcp_tool": "strata_capabilities"
      }
    },
    {
      "id": "discover_markets",
      "kind": "discovery",
      "summary": "Discover ready markets, token decimals, and public operation paths.",
      "required_capabilities": [
        "markets.read"
      ],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/sonar/markets",
        "mcp_tool": "strata_markets"
      }
    },
    {
      "id": "discover_action_graph",
      "kind": "discovery",
      "summary": "Read the executable topology, live node availability, external signing steps, and transition conditions.",
      "required_capabilities": [],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/sonar/action-graph",
        "mcp_tool": "strata_action_graph"
      }
    },
    {
      "id": "discover_platform_capabilities",
      "kind": "discovery",
      "summary": "Read the versioned capabilities available through the official SDK.",
      "required_capabilities": [],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/v2/capabilities"
      }
    },
    {
      "id": "discover_platform_markets",
      "kind": "discovery",
      "summary": "Discover opaque market IDs and current market status.",
      "required_capabilities": [
        "markets.read"
      ],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/v2/markets"
      }
    },
    {
      "id": "read_book",
      "kind": "read",
      "summary": "Read a sequenced Strata book snapshot.",
      "required_capabilities": [
        "books.read"
      ],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/v2/markets/{market_id}/book"
      }
    },
    {
      "id": "read_market_status",
      "kind": "read",
      "summary": "Read tick size, minimum order size, and current market status.",
      "required_capabilities": [
        "books.read"
      ],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/v2/markets/{market_id}/status"
      }
    },
    {
      "id": "read_best_bid_ask",
      "kind": "read",
      "summary": "Read the current best bid and ask.",
      "required_capabilities": [
        "books.read"
      ],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/v2/markets/{market_id}/bbo"
      }
    },
    {
      "id": "read_fees",
      "kind": "read",
      "summary": "Read the market fee schedule.",
      "required_capabilities": [
        "books.read"
      ],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/v2/markets/{market_id}/fees"
      }
    },
    {
      "id": "read_trades",
      "kind": "read",
      "summary": "Read recent anonymized trades.",
      "required_capabilities": [
        "books.read"
      ],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/v2/markets/{market_id}/trades"
      }
    },
    {
      "id": "stream_market",
      "kind": "read",
      "summary": "Subscribe to book changes, trades, and heartbeats with automatic recovery.",
      "required_capabilities": [
        "books.read"
      ],
      "available": true,
      "operation": {
        "method": "WEBSOCKET",
        "path": "/v2/markets/{market_id}/stream"
      }
    },
    {
      "id": "authorize_account_read",
      "kind": "external_signature",
      "summary": "The agent owner's configured signer authorizes the exact account request or stream challenge.",
      "required_capabilities": [],
      "available": true
    },
    {
      "id": "read_account",
      "kind": "read",
      "summary": "Read the owner's sanitized open orders and fills for a Strata market.",
      "required_capabilities": [
        "account.read"
      ],
      "available": true,
      "operation": {
        "method": "GET",
        "path": "/v2/markets/{market_id}/account/{wallet_address}"
      }
    },
    {
      "id": "stream_account",
      "kind": "read",
      "summary": "Subscribe to signed, sequenced order and fill state for the owner.",
      "required_capabilities": [
        "account.read"
      ],
      "available": true,
      "operation": {
        "method": "WEBSOCKET",
        "path": "/v2/markets/{market_id}/account/{wallet_address}/stream"
      }
    },
    {
      "id": "request_quote",
      "kind": "read",
      "summary": "Request economics bound to a market, side, exact input atoms, and tolerance.",
      "required_capabilities": [
        "quotes.read"
      ],
      "available": true,
      "operation": {
        "method": "POST",
        "path": "/sonar/markets/{market}/quote",
        "mcp_tool": "strata_quote"
      }
    },
    {
      "id": "request_execution_challenge",
      "kind": "prepare",
      "summary": "Request canonical authorization bytes for an unexpired quote and external signer.",
      "required_capabilities": [
        "trade.prepare"
      ],
      "available": true,
      "operation": {
        "method": "POST",
        "path": "/sonar/markets/{market}/execution/challenge",
        "mcp_tool": "strata_execution_challenge"
      }
    },
    {
      "id": "sign_authorization",
      "kind": "external_signature",
      "summary": "The agent owner's configured signer signs the returned authorization bytes externally.",
      "required_capabilities": [],
      "available": true
    },
    {
      "id": "prepare_execution",
      "kind": "prepare",
      "summary": "Exchange the authorization signature for a quote-bound partially signed transaction.",
      "required_capabilities": [
        "trade.prepare"
      ],
      "available": true,
      "operation": {
        "method": "POST",
        "path": "/sonar/markets/{market}/execution/prepare",
        "mcp_tool": "strata_execution_prepare"
      }
    },
    {
      "id": "sign_transaction",
      "kind": "external_signature",
      "summary": "The external signer verifies and fills its signature slot without sending key material to Strata.",
      "required_capabilities": [],
      "available": true
    },
    {
      "id": "submit_execution",
      "kind": "submit",
      "summary": "Submit the signed transaction with an idempotency key.",
      "required_capabilities": [
        "trade.submit"
      ],
      "available": true,
      "operation": {
        "method": "POST",
        "path": "/sonar/markets/{market}/execution/submit",
        "mcp_tool": "strata_execution_submit"
      }
    },
    {
      "id": "receive_receipt",
      "kind": "receipt",
      "summary": "Receive the execution ID, Solana signature, and submitted status.",
      "required_capabilities": [],
      "available": true
    }
  ],
  "edges": [
    {
      "from": "discover_capabilities",
      "to": "discover_action_graph",
      "condition": "the returned contract version is supported"
    },
    {
      "from": "discover_action_graph",
      "to": "discover_markets",
      "condition": "markets.read is enabled"
    },
    {
      "from": "discover_action_graph",
      "to": "discover_platform_capabilities",
      "condition": "the versioned SDK contract is supported"
    },
    {
      "from": "discover_platform_capabilities",
      "to": "discover_platform_markets",
      "condition": "markets.read is enabled"
    },
    {
      "from": "discover_platform_markets",
      "to": "read_book",
      "condition": "books.read is enabled and the market is active"
    },
    {
      "from": "discover_platform_markets",
      "to": "read_market_status",
      "condition": "books.read is enabled"
    },
    {
      "from": "discover_platform_markets",
      "to": "read_best_bid_ask",
      "condition": "books.read is enabled"
    },
    {
      "from": "discover_platform_markets",
      "to": "read_fees",
      "condition": "books.read is enabled"
    },
    {
      "from": "discover_platform_markets",
      "to": "read_trades",
      "condition": "books.read is enabled"
    },
    {
      "from": "read_book",
      "to": "stream_market",
      "condition": "books.read is enabled and the snapshot sequence is accepted"
    },
    {
      "from": "discover_platform_markets",
      "to": "authorize_account_read",
      "condition": "account.read is enabled and the owner-configured signer is available"
    },
    {
      "from": "authorize_account_read",
      "to": "read_account",
      "condition": "the signature binds the wallet, market, request time, and fill limit"
    },
    {
      "from": "read_account",
      "to": "stream_account",
      "condition": "the stream challenge is signed by the same owner-configured signer"
    },
    {
      "from": "discover_markets",
      "to": "request_quote",
      "condition": "quotes.read is enabled and the market is ready"
    },
    {
      "from": "request_quote",
      "to": "request_execution_challenge",
      "condition": "trade.prepare is enabled and the quote is unexpired"
    },
    {
      "from": "request_execution_challenge",
      "to": "sign_authorization",
      "condition": "the challenge bindings match the quote and signer"
    },
    {
      "from": "sign_authorization",
      "to": "prepare_execution",
      "condition": "a valid external authorization signature is available"
    },
    {
      "from": "prepare_execution",
      "to": "sign_transaction",
      "condition": "the prepared transaction preserves the signed bindings"
    },
    {
      "from": "sign_transaction",
      "to": "submit_execution",
      "condition": "trade.submit is enabled and the signed transaction is unmodified"
    },
    {
      "from": "submit_execution",
      "to": "receive_receipt",
      "condition": "the execution ID and idempotency key match"
    }
  ]
} as const;

export const STRATA_ACTION_GRAPH_URI = "strata://action-graph/v1";

export const STRATA_AGENT_HARNESS_INSTRUCTIONS = "Strata Agent Harness 1.0. Start every objective with strata_capabilities, then strata_action_graph, then strata_markets. Read strata://agent-harness/v1 and strata://action-graph/v1. The external agent owner controls permission and signer authority. Strata accepts public keys, detached signatures, and signed transactions, never private keys or seed phrases. Resolve the market, side, exact input atoms, and tolerance before strata_quote. Treat amounts as unsigned base-10 token atoms; check quote bindings, labelled fees, minimum output, and expiry. To execute: request a challenge, sign its canonical authorization bytes externally, prepare, verify and sign the returned transaction externally, then submit with idempotency. Stop on ambiguity, unavailable capabilities, paused markets, unsupported contracts, inconsistent bindings, expiry, or missing signer authority.";
