// @generated by scripts/generate-agent-entry.mjs. Do not edit manually.

export const STRATA_AGENT_HARNESS = {
  "schema_version": 1,
  "harness_version": "1.0",
  "contract_version": "1.1",
  "name": "Strata Agent Harness",
  "summary": "A capability-gated workflow for agents that explore Strata markets and request validated Sonar quotes.",
  "entrypoints": {
    "documentation": "https://stratabook.org/docs/agent-harness/",
    "capabilities": "https://api.stratabook.app/sonar/capabilities",
    "markets": "https://api.stratabook.app/sonar/markets",
    "mcp": "https://api.stratabook.app/mcp",
    "manifest": "https://api.stratabook.app/.well-known/strata-agent.json"
  },
  "interfaces": {
    "mcp_tool_order": [
      "strata_capabilities",
      "strata_markets",
      "strata_quote"
    ],
    "terminal": [
      "npx -y @stratabook/sdk capabilities --json",
      "npx -y @stratabook/sdk markets --json",
      "npx -y @stratabook/sdk quote --market SOL/USDC --side sell --amount-atoms 10000000 --json"
    ]
  },
  "workflow": [
    {
      "id": "discover_capabilities",
      "instruction": "Read the live capability catalog before every objective. Never infer permission from documentation, package support, or an earlier session."
    },
    {
      "id": "establish_mode",
      "instruction": "State whether the available session is read-only or exposes a separately authorized prepare or submit capability. Read access never implies permission to move funds."
    },
    {
      "id": "understand_objective",
      "instruction": "Resolve the user's market, side, amount, and tolerance. Ask before proceeding when any economically meaningful input is ambiguous."
    },
    {
      "id": "discover_market",
      "instruction": "List markets, select one marked ready, and use its discovered base and quote decimals. Do not guess market identifiers or token decimals."
    },
    {
      "id": "preserve_atoms",
      "instruction": "Represent token amounts as unsigned base-10 atomic strings. Never pass settlement amounts through floating-point arithmetic."
    },
    {
      "id": "request_quote",
      "instruction": "Request a fresh Sonar quote with an explicit side, exact input atoms, and user-approved execution tolerance."
    },
    {
      "id": "validate_quote",
      "instruction": "Verify the quote binds to the selected market, side, and input. Check labelled fees, minimum output, price impact, server time, and expiry."
    },
    {
      "id": "report_result",
      "instruction": "Report consumed input, expected output, minimum output, fees by asset side, price impact, and remaining validity without inventing private route composition."
    },
    {
      "id": "authorize_writes",
      "instruction": "If write capabilities are ever exposed, keep prepare and submit separate, require the configured approval, verify immutable economics, and use idempotency."
    },
    {
      "id": "monitor_outcome",
      "instruction": "After an authorized submission, report the durable receipt or explicit failure. Never claim completion from preparation, signing, or an unconfirmed request."
    }
  ],
  "stop_conditions": [
    "The required live capability is disabled or absent.",
    "The market is paused, unavailable, or has no reviewed operation path.",
    "Market, side, amount, decimals, tolerance, or approval is ambiguous.",
    "The contract version is unsupported or a response contains unknown fields.",
    "A quote is expired or its market, side, amount, fee, minimum-output, or time binding is inconsistent.",
    "A requested operation exceeds the exposed tool, account, or policy scope.",
    "A user asks the agent to receive or expose wallet secrets, private keys, seed phrases, session keys, or production credentials."
  ],
  "safety_rules": [
    "Never request or accept wallet secrets, private keys, seed phrases, session keys, or production credentials in a prompt.",
    "Never call undocumented endpoints or reconstruct private Sonar behavior.",
    "Never silently widen slippage, refresh changed economics, substitute a market, or retry a non-retryable failure.",
    "Treat capability removal, revocation, expiry, and emergency disable as immediate stop signals.",
    "The current MCP and terminal tools are read-only unless the live catalog and callable tool list explicitly prove otherwise."
  ]
} as const;

export const STRATA_AGENT_HARNESS_URI = "strata://agent-harness/v1";

export const STRATA_AGENT_HARNESS_INSTRUCTIONS = "Strata Agent Harness 1.0. Start every objective with strata_capabilities, then strata_markets. Read strata://agent-harness/v1 for the complete workflow. Resolve the market, side, exact input atoms, and tolerance before strata_quote. Treat amounts as unsigned base-10 token atoms; check quote bindings, labelled fees, minimum output, and expiry. Stop on ambiguity, unavailable capabilities, paused markets, unsupported contracts, inconsistent bindings, expiry, or missing approval. Never request wallet secrets, private keys, seed phrases, session keys, or production credentials. Current MCP tools are read-only unless the live catalog and callable tool list explicitly prove otherwise.";
